### ISSUE TITLE
Biffbot.parse is throwing "Malformed url query string argument." error

### ISSUE THREAD

**Issue by mpurusottamc** [tevren/biffbot#3]
Hi,

I am using the below statement and getting "Malformed url query..." error :
biff = Biffbot::Base.new
article = biff.parse Settings.BiffbotToken, 'article', url, options

Here url is : http%253A%252F%252Fwww.theguardian.com%252Ftechnology%252F2015%252Fjul%252F14%252Fgoogle-accidentally-reveals-right-to-be-forgotten-requests
The final URL is : "http://api.diffbot.com/v3/article?token=mytoken&url=http%253A%252F%252Fwww.theguardian.com%252Ftechnology%252F2015%252Fjul%252F14%252Fgoogle-accidentally-reveals-right-to-be-forgotten-requests"

Please help me understand if i am doing something wrong here.

**Comment by jdrago999** [comment]
Super late (currently > 2 years after your post) but: your `url=` parameter value was double-url-encoded, and only needed to be single-url-encoded.

The correct url should have been:

```
http://api.diffbot.com/v3/article?token=mytoken&url=http%3A%2F%2Fwww.theguardian.com%2Ftechnology%2F2015%2Fjul%2F14%2Fgoogle-accidentally-reveals-right-to-be-forgotten-requests
```
